#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push "nasyalnik/cats-ui:travis-$TRAVIS_BUILD_NUMBER"
ssh -i ./deploy_key "$PRODUCTION_USER@$PRODUCTION_SERVER" << EOF
    (docker rm -f cats-ui) || true
    docker run -d \
        --name cats-ui \
        --network meowle \
        --restart always \
        -e NODE_ENV=production \
        -e API_URI=http://cats-api:3001 \
        -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER \
        -l traefik.enable=true \
        -l "traefik.http.routers.cats_ui.rule=Host(\\\`meowle.testops.ru\\\`,\\\`www.meowle.testops.ru\\\`)" \
        -l traefik.http.routers.cats_ui.entrypoints=websecure \
        -l traefik.http.routers.cats_ui.tls.certresolver=testops \
        -l "traefik.http.routers.cats_ui_insecure.rule=Host(\\\`meowle.testops.ru\\\`,\\\`www.meowle.testops.ru\\\`)" \
        -l traefik.http.routers.cats_ui_insecure.entrypoints=web \
        -l traefik.http.routers.cats_ui_insecure.middlewares=redirect_to_https \
        -l traefik.http.middlewares.redirect_to_https.redirectscheme.scheme=https \
        "nasyalnik/cats-ui:travis-$TRAVIS_BUILD_NUMBER"
EOF
